# Generated by Django 5.0.6 on 2024-10-06 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_trait_alibi_interaction'),
        ('gameplay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text="The player's chosen nickname.", max_length=100)),
                ('character', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='characters.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Description of the action taken.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phase', models.IntegerField(help_text='The game phase during which the action occurred.')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerClue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_revealed', models.BooleanField(default=False)),
                ('clue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.clue')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('eliminated', 'Eliminated')], default='active', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='players.player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_sessions', to='gameplay.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('phase', models.IntegerField(help_text='The game phase during which the vote occurred.')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='players.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='players.player')),
            ],
        ),
    ]
