# Generated by Django 5.1.1 on 2024-10-06 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('role', models.CharField(help_text="Character's role in the story, e.g., detective, victim.", max_length=50)),
                ('backstory', models.TextField(help_text='Backstory that might give clues or add flavor')),
                ('secret', models.TextField(blank=True, help_text='Any sectret information specific to the character', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('phase', models.IntegerField(help_text='Game phase during which the clue is revealed.')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(help_text='Relationship type, e.g., friends, rivals, siblings.', max_length=50)),
                ('character_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='characters.character')),
                ('character_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='characters.character')),
            ],
        ),
    ]
